### ISSUE TITLE
Gate ControlledQubitUnitary not supported on device braket.local.qubit

### ISSUE THREAD

**Issue by ankit27kh** [aws/amazon-braket-pennylane-plugin-python#137]
**Describe the bug**
It mentions on the plugin site that all PennyLane operations are supported. https://amazon-braket-pennylane-plugin-python.readthedocs.io/en/latest/devices/braket_local.html#supported-operations

While running the QuantumPhaseEstimation template from Pennylane on the local device, this error is raised:
 
```
raise DeviceError(
pennylane._device.DeviceError: Gate ControlledQubitUnitary not supported on device braket.local.qubit
```

**To reproduce**
Use qml.QuantumPhaseEstimation

**Expected behavior**
Circuit should run without error.

**Screenshots or logs**
N/A

**System information**
A description of your system. Please provide:
- **Amazon Braket Python PennyLane Plugin version**:1.11.2.post0
- **Amazon Braket Python SDK version**:1.35.5
- **Amazon Braket Python Schemas version**:1.14.1.post0
- **Amazon Braket Python Default Simulator version**:1.11.5.post0
- **Python version**:3.9.16

**Additional context**
N/A

**Comment by speller26** [comment]
Thank you for the issue, and good catch; that documentation is out-of-date. We have since added new operations to the plugin, such as GPi and MS. As well, PennyLane added several new operations, and the plugin doesn't support all of them (for example, `ControlledQubitUnitary`). If your use case allows it, you'll need to use `QubitUnitary` with the full matrix of the controlled operation.
